<?php die(); ?><!DOCTYPE html>
<!--[if IE 8]>
<html xmlns="http://www.w3.org/1999/xhtml" class="ie8" lang="en-US">
<![endif]-->
<!--[if !(IE 8) ]><!-->
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
<!--<![endif]-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Marcus Graham &rsaquo; Log In</title>
    <link rel='stylesheet' id='dashicons-css'  href='http://marcusgrahamproject.org/mg-rebuild/wp-includes/css/dashicons.min.css' type='text/css' media='all' />
<link rel='stylesheet' id='buttons-css'  href='http://marcusgrahamproject.org/mg-rebuild/wp-includes/css/buttons.min.css' type='text/css' media='all' />
<link rel='stylesheet' id='forms-css'  href='http://marcusgrahamproject.org/mg-rebuild/wp-admin/css/forms.min.css' type='text/css' media='all' />
<link rel='stylesheet' id='l10n-css'  href='http://marcusgrahamproject.org/mg-rebuild/wp-admin/css/l10n.min.css' type='text/css' media='all' />
<link rel='stylesheet' id='login-css'  href='http://marcusgrahamproject.org/mg-rebuild/wp-admin/css/login.min.css' type='text/css' media='all' />
        <script>if("sessionStorage" in window){try{for(var key in sessionStorage){if(key.indexOf("wp-autosave-")!=-1){sessionStorage.removeItem(key)}}}catch(e){}};</script>
    <link rel='dns-prefetch' href='//s.w.org' />
<script type='text/javascript' src='http://marcusgrahamproject.org/mg-rebuild/wp-admin/load-scripts.php?c=0&amp;load%5B%5D=jquery-core,jquery-migrate&amp;ver=4.6.1'></script>
<script type='text/javascript' src='http://marcusgrahamproject.org/mg-rebuild/wp-content/plugins/better-wp-security/core/modules/strong-passwords/js/script.js'></script>
<style type="text/css">
        .login h1 a {
          width: 222px !important;
          height: 49px !important;
          background-image:url(http://marcusgrahamproject.org/mg-rebuild/wp-content/themes/smarty-child/assets/images/mgp_logo_black.png) !important;
          background-size: cover;
        }
  </style><meta name='robots' content='noindex,follow' />
<link rel="icon" href="http://marcusgrahamproject.org/mg-rebuild/wp-content/uploads/2016/10/mgfavicon.jpg" sizes="32x32" />
<link rel="icon" href="http://marcusgrahamproject.org/mg-rebuild/wp-content/uploads/2016/10/mgfavicon.jpg" sizes="192x192" />
<link rel="apple-touch-icon-precomposed" href="http://marcusgrahamproject.org/mg-rebuild/wp-content/uploads/2016/10/mgfavicon.jpg" />
<meta name="msapplication-TileImage" content="http://marcusgrahamproject.org/mg-rebuild/wp-content/uploads/2016/10/mgfavicon.jpg" />
</head>
<body class="login login-action- wp-core-ui  locale-en-us">
<div id="login">
    <h1><a href="https://wordpress.org/" title="Marcus Graham Project" tabindex="-1">Marcus Graham</a></h1>
    <p class="message">	You are now logged out.<br />
</p>

<form name="loginform" id="loginform" action="http://marcusgrahamproject.org/mg-rebuild/mgpro2016/" method="post">
	<p>
		<label for="user_login">Username or Email<br />
		<input type="text" name="log" id="user_login" aria-describedby="login_error" class="input" value="" size="20" /></label>
	</p>
	<p>
		<label for="user_pass">Password<br />
		<input type="password" name="pwd" id="user_pass" aria-describedby="login_error" class="input" value="" size="20" /></label>
	</p>
	<p>Login form protected by <a href='http://www.bad-neighborhood.com/login-lockdown.html' rel='nofollow'>Login LockDown</a>.<br /><br /><br /></p>	<p class="forgetmenot"><label for="rememberme"><input name="rememberme" type="checkbox" id="rememberme" value="forever"  /> Remember Me</label></p>
	<p class="submit">
		<input type="submit" name="wp-submit" id="wp-submit" class="button button-primary button-large" value="Log In" />
        <input type="hidden" name="redirect_to" value="http://marcusgrahamproject.org/mg-rebuild/wp-admin/" />
            		<input type="hidden" name="testcookie" value="1" />
	</p>
</form>

        <p id="nav">
                            <a href="http://marcusgrahamproject.org/mg-rebuild/mgpro2016/?action=lostpassword" title="Password Lost and Found">Lost your password?</a>
                    </p>
    
<script type="text/javascript">
function wp_attempt_focus(){
setTimeout( function(){ try{
        d = document.getElementById('user_login');
        d.focus();
d.select();
} catch(e){}
}, 200);
}

if(typeof wpOnload=='function')wpOnload();
</script>

        <p id="backtoblog"><a href="http://marcusgrahamproject.org/mg-rebuild/" title="Are you lost?">&larr; Back to Marcus Graham</a></p>
    
</div>


<div class="clear"></div>
</body>
</html>

<!-- Dynamic page generated in 0.940 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-01-20 12:38:44 -->
